# Generated by Django 4.1.1 on 2022-10-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_hub',
            field=models.BooleanField(default=True),
        ),
    ]
