# Generated by Django 4.1.1 on 2022-11-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_hubmeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HubMeta',
            new_name='FranchiseMeta',
        ),
    ]
