# Generated by Django 4.1.1 on 2022-11-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_rename_hubmeta_franchisemeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchisemeta',
            old_name='four_years_store_price',
            new_name='five_years_store_price',
        ),
    ]
