# Generated by Django 4.1.1 on 2022-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0005_rename_four_years_store_price_franchisemeta_five_years_store_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('youtube_video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Settings',
                'verbose_name_plural': 'Content Settings',
            },
        ),
    ]
