# Generated by Django 4.1.1 on 2022-11-27 10:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_contentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsettings',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentsettings',
            name='privacy_policy',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentsettings',
            name='terms',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
