# Generated by Django 4.1.1 on 2022-12-01 03:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_contactus_generalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowThisWorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', tinymce.models.HTMLField(blank=True, null=True)),
                ('business_strategy', tinymce.models.HTMLField(blank=True, null=True)),
                ('goodKnow', tinymce.models.HTMLField(blank=True, null=True)),
                ('youtube_video_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'How This Work',
                'verbose_name_plural': 'How This Work',
            },
        ),
        migrations.RemoveField(
            model_name='contentsettings',
            name='about',
        ),
        migrations.RemoveField(
            model_name='contentsettings',
            name='youtube_video_link',
        ),
    ]
