# Generated by Django 4.1.1 on 2022-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_howthisworksettings_remove_contentsettings_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
