# Generated by Django 4.1.1 on 2022-12-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_address_full_address_address_lat_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
