# Generated by Django 4.1.1 on 2022-12-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0011_alter_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ehubUser',
            field=models.ForeignKey(blank=True, help_text="Please don't fill this field when creating address", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ehub_user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='is_hired',
            field=models.BooleanField(default=False, help_text="Please don't fill this field when creating address"),
        ),
    ]
