# Generated by Django 4.1.1 on 2022-12-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_ehubpurchaseperson_date'),
        ('meta', '0013_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hub_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_hub_user', to='user.ehubinfo'),
        ),
    ]
