# Generated by Django 4.1.1 on 2022-12-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_address_hub_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
