# Generated by Django 4.1.1 on 2022-12-22 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_userdetails_requested_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0015_address_office_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ehubUser',
        ),
        migrations.AddField(
            model_name='address',
            name='hub_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_hub_info', to='user.ehubinfo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='hub_user',
            field=models.ForeignKey(blank=True, help_text="Please don't fill this field when creating address", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ehub_user_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
