# Generated by Django 4.1.1 on 2022-12-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0016_remove_address_ehubuser_address_hub_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='population',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
