# Generated by Django 4.1.1 on 2022-12-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0017_address_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFranchiseAddressProxyModel',
            fields=[
            ],
            options={
                'verbose_name': ' E-Franchise Address',
                'verbose_name_plural': ' E-Franchise Address',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meta.address',),
        ),
        migrations.CreateModel(
            name='HubAddressProxyModel',
            fields=[
            ],
            options={
                'verbose_name': ' E-Hub Address',
                'verbose_name_plural': ' E-Hub Address',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meta.address',),
        ),
    ]
