# Generated by Django 4.1.1 on 2022-12-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_efranchiseaddressproxymodel_hubaddressproxymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_hub',
            field=models.BooleanField(default=False),
        ),
    ]
