# Generated by Django 4.1.1 on 2022-10-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_referral_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreport',
            name='company_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='referralreport',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
