# Generated by Django 4.1.1 on 2022-10-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_referralreport_company_profit_referralreport_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='referredperson',
            name='referred_person_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
