# Generated by Django 4.1.1 on 2022-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_alter_referral_options_alter_referralreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='total_referral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
    ]
