# Generated by Django 4.1.1 on 2022-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_referral_total_referral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='minimum_purchase_per_user',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
    ]
