# Generated by Django 4.1.1 on 2022-12-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0008_alter_referral_minimum_purchase_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='referredperson',
            name='referred_person_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referredperson',
            name='referred_person_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
