# Generated by Django 4.1.1 on 2022-10-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_remove_bankaccount_withdraw_withdraw_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
