# Generated by Django 4.1.1 on 2022-10-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_bankaccount_bank_area_bankaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-created_at']},
        ),
    ]
