# Generated by Django 4.1.1 on 2022-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0004_alter_withdraw_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='short_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
