# Generated by Django 4.1.1 on 2022-09-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address_alter_efranchiseinfo_five_years_store_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
    ]
