# Generated by Django 4.1.1 on 2022-09-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='citizen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
