# Generated by Django 4.1.1 on 2022-09-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdetails_address_userdetails_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehubinfo',
            name='space_type',
            field=models.CharField(blank=True, choices=[('FEET', 'Squire Feet'), ('FLOOR', 'Floor')], max_length=20, null=True),
        ),
    ]
