# Generated by Django 4.1.1 on 2022-09-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_ehubinfo_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='eFranchiseAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='efranchise_address', to='user.efranchiseinfo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='eHubAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ehub_address', to='user.ehubinfo'),
        ),
    ]
