# Generated by Django 4.1.1 on 2022-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_resetpassword_activeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
