# Generated by Django 4.1.1 on 2022-10-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHubReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('number_of_sells_product', models.IntegerField(default=0)),
                ('total_amount_of_sells_product', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('active', models.BooleanField(default=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_report', to='user.ehubinfo')),
            ],
        ),
    ]
