# Generated by Django 4.1.1 on 2022-10-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_ehubreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='citizen',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
