# Generated by Django 4.1.1 on 2022-10-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userdetails_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efranchiseinfo',
            name='total_liquid_assets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='efranchiseinfo',
            name='total_net_worth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='citizen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
