# Generated by Django 4.1.1 on 2022-10-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_address_user_alter_efranchiseinfo_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHubPurchasePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_person_name', models.CharField(max_length=50)),
                ('referred_person_id', models.CharField(max_length=50)),
                ('referred_person_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('number_of_sells_product', models.IntegerField(default=0)),
                ('total_amount_of_sells_product', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_person', to='user.ehubinfo')),
            ],
        ),
    ]
