# Generated by Django 4.1.1 on 2022-10-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_ehubpurchaseperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ehubpurchaseperson',
            old_name='referred_person_email',
            new_name='person_email',
        ),
        migrations.RenameField(
            model_name='ehubpurchaseperson',
            old_name='referred_person_id',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='ehubpurchaseperson',
            old_name='referred_person_name',
            new_name='person_name',
        ),
    ]
