# Generated by Django 4.1.1 on 2022-10-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_referred_person_email_ehubpurchaseperson_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehubpurchaseperson',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='file/ehub/invoice/%Y/%m/%d/'),
        ),
    ]
