# Generated by Django 4.1.1 on 2022-11-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_ehubpurchaseperson_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseUserNewRequestProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'E-Franchise User Request',
                'verbose_name_plural': 'E-Franchise User Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
