# Generated by Django 4.1.1 on 2022-11-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_franchiseusernewrequestproxymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubUserNewRequestProxyModel',
            fields=[
            ],
            options={
                'verbose_name': '  E-Hub User Request',
                'verbose_name_plural': '  E-Hub User Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.AlterModelOptions(
            name='franchiseusernewrequestproxymodel',
            options={'verbose_name': ' E-Franchise User Request', 'verbose_name_plural': ' E-Franchise User Requests'},
        ),
    ]
