# Generated by Django 4.1.1 on 2022-11-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_hubusernewrequestproxymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseNewUserProxyModel',
            fields=[
            ],
            options={
                'verbose_name': '   E-Franchise New User',
                'verbose_name_plural': '   E-Franchise New User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='HubNewUserProxyModel',
            fields=[
            ],
            options={
                'verbose_name': '   E-Hub New User',
                'verbose_name_plural': '   E-Hub New User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_at',), 'verbose_name': ' Address', 'verbose_name_plural': ' Address'},
        ),
        migrations.AlterModelOptions(
            name='efranchiseinfo',
            options={'verbose_name': ' EFranchise Info', 'verbose_name_plural': ' EFranchise Info'},
        ),
        migrations.AlterModelOptions(
            name='ehubinfo',
            options={'verbose_name': ' EHub Info', 'verbose_name_plural': ' EHub Info'},
        ),
        migrations.AlterModelOptions(
            name='franchiseusernewrequestproxymodel',
            options={'verbose_name': '      E-Franchise User Request', 'verbose_name_plural': '      E-Franchise User Requests'},
        ),
        migrations.AlterModelOptions(
            name='hubusernewrequestproxymodel',
            options={'verbose_name': '     E-Hub User Request', 'verbose_name_plural': '     E-Hub User Requests'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '   User', 'verbose_name_plural': '   Users'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': '  User Details', 'verbose_name_plural': '  User Details'},
        ),
    ]
