# Generated by Django 4.1.1 on 2022-11-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_franchisenewuserproxymodel_hubnewuserproxymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchisenewuserproxymodel',
            options={'verbose_name': '   E-Franchise User', 'verbose_name_plural': '   E-Franchise Users'},
        ),
        migrations.AlterModelOptions(
            name='hubnewuserproxymodel',
            options={'verbose_name': '   E-Hub User', 'verbose_name_plural': '   E-Hub Users'},
        ),
    ]
