# Generated by Django 4.1.1 on 2022-12-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_franchisenewuserproxymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehubpurchaseperson',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
