# Generated by Django 4.1.1 on 2022-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userdetails_hub_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='hub_address',
        ),
        migrations.AddField(
            model_name='ehubinfo',
            name='office_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
