# Generated by Django 4.1.1 on 2022-12-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_userdetails_hub_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
    ]
