# Generated by Django 4.1.1 on 2022-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_userdetails_requested_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehubpurchaseperson',
            name='invoice',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
